export const projects = [
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 1,
    img: "https://bardahl.am/ru/wp-content/uploads/sites/4/revslider/slider-11/asset2.png",
    title: "Շաչջիչի յուղ",
    model: "Bardal",
    price: "4000",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 2,
    img: "https://rally.am/views/images/autopart/3609/img_large/3609_1643314307.jpg",
    title: "Անտիֆրիզ",
    model: "Polar",
    price: "1500",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 3,
    img: "https://a.d-cd.net/e9925c8s-960.jpg",
    title: "Расширительный бачок",
    model: "Opel Zafira",
    price: "35000",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 4,
    img: "https://rally.am/views/images/autopart/256/img_large/256_1550474018.jpg",
    title: "Ետևի լուսարձակ",
    model: "Mercedece",
    price: "45000",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 5,
    img: "https://s.list.am/f/651/61245651.webp",
    title: "Լամպ",
    model: "Niken",
    price: "8000",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 6,
    img: "https://amastercar.ru/articles/img/brake.jpg",
    title: "Тормозные колодки",
    model: "Piduyl",
    price: "12000",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 6,
    img: "https://amastercar.ru/articles/img/brake.jpg",
    title: "Тормозные колодки",
    model: "Piduyl",
    price: "12000",
  },
  {
    lastUpdated: "March 17, 2020",
    bgColorClass: "bg-pink-600",
    id: 8,
    img: "https://amastercar.ru/img/komressor_shin.jpg",
    title: "Նասոս",
    model: "Deford",
    price: "5000",
  },
];

